// Frases motivacionais/filosóficas exibidas (rotativas, aleatórias) no painel
// direito do login. q = frase, a = autor/fonte. As três listas ficam mescladas
// num único pool.

export type Frase = { q: string; a: string };

export const FRASES: Frase[] = [
	// ---- Lista 1 ----
	{ q: 'Conhece-te a ti mesmo.', a: 'Sócrates' },
	{ q: 'Penso, logo existo.', a: 'René Descartes' },
	{ q: 'O homem é aquilo que faz repetidamente.', a: 'Aristóteles' },
	{ q: 'Quem tem um porquê enfrenta qualquer como.', a: 'Friedrich Nietzsche' },
	{ q: 'A sorte favorece os preparados.', a: 'Provérbio atribuído a Sêneca' },
	{ q: 'A vida é feita de escolhas.', a: 'The Matrix' },
	{ q: 'Faça ou não faça. Tentativa não existe.', a: 'Star Wars: Episode V – The Empire Strikes Back' },
	{ q: 'Com grandes poderes vêm grandes responsabilidades.', a: 'Spider-Man' },
	{ q: 'Até a menor pessoa pode mudar o futuro.', a: 'The Lord of the Rings: The Fellowship of the Ring' },
	{ q: 'A esperança é uma coisa boa.', a: 'The Shawshank Redemption' },
	{ q: 'Você se torna aquilo que repete.', a: 'Aristóteles' },
	{ q: 'O impossível é uma opinião.', a: 'Paulo Vieira' },
	{ q: 'O sucesso deixa pistas.', a: 'Paulo Vieira' },
	{ q: 'Resultado é consequência de decisão.', a: 'Joel Jota' },
	{ q: 'Disciplina vence motivação.', a: 'Joel Jota' },
	{ q: 'Quem acelera, chega.', a: 'Pablo Marçal' },
	{ q: 'Pare de negociar com a sua desculpa.', a: 'Pablo Marçal' },
	{ q: 'O medo é um péssimo conselheiro.', a: 'Ditado popular' },
	{ q: 'A ação cura o medo.', a: 'David J. Schwartz' },
	{ q: 'A coragem vem antes da confiança.', a: 'Robin Sharma' },
	{ q: 'Quem olha para fora sonha; quem olha para dentro desperta.', a: 'Carl Gustav Jung' },
	{ q: 'Tudo depende da forma como você vê.', a: 'Epicteto' },
	{ q: 'A felicidade depende de nós.', a: 'Aristóteles' },
	{ q: 'O hábito molda o destino.', a: 'Aristóteles' },
	{ q: 'Quem domina a si mesmo é invencível.', a: 'Lao Tsé' },
	{ q: 'A simplicidade é o auge da sofisticação.', a: 'Leonardo da Vinci' },
	{ q: 'A dúvida é o princípio da sabedoria.', a: 'Aristóteles' },
	{ q: 'A persistência realiza o impossível.', a: 'Provérbio' },
	{ q: 'Grandes mudanças começam pequenas.', a: 'Ideia popular' },
	{ q: 'Não espere. Construa.', a: 'Inspiração contemporânea' },
	{ q: 'Seu futuro começa hoje.', a: 'Frase motivacional' },
	{ q: 'O tempo revela tudo.', a: 'Sófocles' },
	{ q: 'Quem planta disciplina colhe liberdade.', a: 'Jim Rohn' },
	{ q: 'A excelência é uma escolha.', a: 'Jim Collins' },
	{ q: 'Você recebe aquilo que tolera.', a: 'Henry Cloud' },
	{ q: 'A mudança começa na mente.', a: 'Carol S. Dweck' },
	{ q: 'A melhor vingança é o sucesso.', a: 'Atribuída a Frank Sinatra' },
	{ q: 'O caráter decide o destino.', a: 'Heráclito' },
	{ q: 'A vitória pertence aos persistentes.', a: 'Atribuída a Napoleão Bonaparte' },
	{
		q: 'A jornada transforma mais que a chegada.',
		a: 'Síntese inspirada em temas clássicos de desenvolvimento pessoal'
	},

	// ---- Lista 2 ----
	{ q: 'A suprema arte da guerra é vencer sem lutar.', a: 'Sun Tzu' },
	{ q: 'Conheça seu inimigo e conheça a si mesmo.', a: 'Sun Tzu' },
	{ q: 'A oportunidade se esconde na dificuldade.', a: 'Confúcio' },
	{ q: 'Mover montanhas começa carregando pedras.', a: 'Confúcio' },
	{ q: 'Quem domina os outros é forte; quem domina a si é poderoso.', a: 'Lao Tsé' },
	{ q: 'A natureza não tem pressa, mas tudo acontece.', a: 'Lao Tsé' },
	{ q: 'A água vence pela persistência.', a: 'Lao Tsé' },
	{ q: 'A disciplina é a mãe da vitória.', a: 'Miyamoto Musashi' },
	{ q: 'Hoje é a vitória sobre você mesmo.', a: 'Miyamoto Musashi' },
	{ q: 'Não faça nada inútil.', a: 'Miyamoto Musashi' },
	{ q: 'A simplicidade é a maior sofisticação.', a: 'Leonardo da Vinci' },
	{ q: 'A experiência nunca erra.', a: 'Leonardo da Vinci' },
	{ q: 'A vitória pertence aos ousados.', a: 'Napoleão Bonaparte' },
	{ q: 'A imaginação governa o mundo.', a: 'Napoleão Bonaparte' },
	{ q: 'Nunca interrompa seu inimigo quando ele estiver errando.', a: 'Napoleão Bonaparte' },
	{ q: 'A liberdade exige responsabilidade.', a: 'George Washington' },
	{ q: 'A perseverança supera o talento.', a: 'Benjamin Franklin' },
	{ q: 'Bem feito é melhor que bem dito.', a: 'Benjamin Franklin' },
	{ q: 'Energia e persistência conquistam tudo.', a: 'Benjamin Franklin' },
	{ q: 'Seja a mudança que deseja ver.', a: 'Mahatma Gandhi' },
	{ q: 'A força nasce da persistência.', a: 'Mahatma Gandhi' },
	{ q: 'Olho por olho torna o mundo cego.', a: 'Mahatma Gandhi' },
	{ q: 'A educação é a arma mais poderosa.', a: 'Nelson Mandela' },
	{ q: 'Sempre parece impossível até acontecer.', a: 'Nelson Mandela' },
	{ q: 'A coragem vence o medo.', a: 'Nelson Mandela' },
	{ q: 'Quem ousa vence.', a: 'Winston Churchill' },
	{ q: 'O sucesso é seguir em frente.', a: 'Winston Churchill' },
	{ q: 'A atitude é uma pequena coisa que faz grande diferença.', a: 'Winston Churchill' },
	{ q: 'O melhor ainda está por vir.', a: 'Ronald Reagan' },
	{ q: 'Confiança é construída diariamente.', a: 'Dwight D. Eisenhower' },
	{ q: 'O preço da grandeza é a responsabilidade.', a: 'Winston Churchill' },
	{ q: 'Sonhos exigem ação.', a: 'Walt Disney' },
	{ q: 'Se você pode sonhar, pode realizar.', a: 'Walt Disney' },
	{ q: 'A inovação distingue líderes.', a: 'Steve Jobs' },
	{ q: 'Continue faminto. Continue ingênuo.', a: 'Steve Jobs' },
	{ q: 'Seu tempo é limitado.', a: 'Steve Jobs' },
	{ q: 'Velocidade importa.', a: 'Bill Gates' },
	{ q: 'O sucesso é um péssimo professor.', a: 'Bill Gates' },
	{ q: 'Quem aprende mais, lidera mais.', a: 'Bill Gates' },
	{ q: 'Assuma riscos calculados.', a: 'Peter Drucker' },
	{ q: 'A cultura vence a estratégia.', a: 'Peter Drucker' },
	{ q: 'O que pode ser medido pode melhorar.', a: 'Peter Drucker' },
	{ q: 'A excelência nunca é um acidente.', a: 'John C. Maxwell' },
	{ q: 'Liderança é influência.', a: 'John C. Maxwell' },
	{ q: 'Você atrai quem você é.', a: 'Paulo Vieira' },
	{ q: 'Sua identidade cria seu destino.', a: 'Paulo Vieira' },
	{ q: 'Quem cresce incomoda.', a: 'Pablo Marçal' },
	{ q: 'A dor é temporária. O legado permanece.', a: 'Joel Jota' },
	{ q: 'Ninguém vence sozinho.', a: 'Andrew Carnegie' },
	{
		q: 'Grandes conquistas começam com pequenas decisões.',
		a: 'Inspirada em princípios clássicos de estratégia e liderança'
	},

	// ---- Lista 3 ----
	{ q: 'A qualidade da sua vida depende das suas perguntas.', a: 'Tony Robbins' },
	{ q: 'Onde vai o foco, flui a energia.', a: 'Tony Robbins' },
	{ q: 'A ação é a ponte entre sonho e realidade.', a: 'Tony Robbins' },
	{ q: 'A clareza precede o sucesso.', a: 'Robin Sharma' },
	{ q: 'Tudo é criado duas vezes: mente e realidade.', a: 'Stephen Covey' },
	{ q: 'Comece com o fim em mente.', a: 'Stephen Covey' },
	{ q: 'O essencial exige coragem.', a: 'Greg McKeown' },
	{ q: 'Menos, porém melhor.', a: 'Greg McKeown' },
	{ q: 'O ego é o inimigo.', a: 'Ryan Holiday' },
	{ q: 'O obstáculo é o caminho.', a: 'Ryan Holiday' },
	{ q: 'A calma é uma superpotência.', a: 'Ryan Holiday' },
	{ q: 'Hábitos pequenos criam destinos grandes.', a: 'James Clear' },
	{ q: 'Você não sobe ao nível das metas.', a: 'James Clear' },
	{ q: 'Você cai ao nível dos seus sistemas.', a: 'James Clear' },
	{ q: 'O que você tolera, você mantém.', a: 'Henry Cloud' },
	{ q: 'Limites protegem propósitos.', a: 'Henry Cloud' },
	{ q: 'Coragem é agir com medo.', a: 'Brené Brown' },
	{ q: 'Vulnerabilidade é força com verdade.', a: 'Brené Brown' },
	{ q: 'A comparação rouba alegria.', a: 'Theodore Roosevelt' },
	{ q: 'Faça o que puder, com o que tiver.', a: 'Theodore Roosevelt' },
	{ q: 'Disciplina é liberdade.', a: 'Jocko Willink' },
	{ q: 'Responsabilidade extrema muda tudo.', a: 'Jocko Willink' },
	{ q: 'A dor ensina rápido.', a: 'David Goggins' },
	{ q: 'Você é mais forte do que pensa.', a: 'David Goggins' },
	{ q: 'A mente desiste antes do corpo.', a: 'David Goggins' },
	{ q: 'Comece antes de estar pronto.', a: 'Marie Forleo' },
	{ q: 'Tudo é solucionável.', a: 'Marie Forleo' },
	{ q: 'Feito é melhor que perfeito.', a: 'Sheryl Sandberg' },
	{ q: 'O medo mata mais sonhos que o fracasso.', a: 'Suzy Kassem' },
	{ q: 'A liderança começa pelo exemplo.', a: 'John Maxwell' },
	{ q: 'Crescimento exige intenção.', a: 'John Maxwell' },
	{ q: 'O líder vê antes dos outros.', a: 'John Maxwell' },
	{ q: 'Sua energia apresenta você primeiro.', a: 'Jay Shetty' },
	{ q: 'Paz também é produtividade.', a: 'Jay Shetty' },
	{ q: 'A mente precisa de direção.', a: 'Jay Shetty' },
	{ q: 'Você se torna suas escolhas.', a: 'Oprah Winfrey' },
	{ q: 'Transforme feridas em sabedoria.', a: 'Oprah Winfrey' },
	{ q: 'O propósito dá peso à rotina.', a: 'Simon Sinek' },
	{ q: 'Comece pelo porquê.', a: 'Simon Sinek' },
	{ q: 'Confiança nasce da consistência.', a: 'Simon Sinek' },
	{ q: 'A execução vence a intenção.', a: 'Gary Vaynerchuk' },
	{ q: 'Paciência também é estratégia.', a: 'Gary Vaynerchuk' },
	{ q: 'Atenção é o novo dinheiro.', a: 'Gary Vaynerchuk' },
	{ q: 'Ideias não executadas são distrações.', a: 'Brendon Burchard' },
	{ q: 'Ambição sem energia vira frustração.', a: 'Brendon Burchard' },
	{ q: 'A excelência é uma identidade.', a: 'Brendon Burchard' },
	{ q: 'Venda é serviço bem comunicado.', a: 'Zig Ziglar' },
	{ q: 'Você não vende produtos, vende transformação.', a: 'Zig Ziglar' },
	{ q: 'A motivação começa com movimento.', a: 'Zig Ziglar' },
	{ q: 'A riqueza segue o valor.', a: 'Jim Rohn' },
	{ q: 'Você é a média das suas influências.', a: 'Jim Rohn' },
	{ q: 'Trabalhe mais em você do que no trabalho.', a: 'Jim Rohn' },
	{ q: 'A mente calma enxerga melhor.', a: 'Eckhart Tolle' },
	{ q: 'O agora é tudo que existe.', a: 'Eckhart Tolle' },
	{ q: 'A presença muda a percepção.', a: 'Eckhart Tolle' },
	{ q: 'Quem controla a atenção controla a vida.', a: 'Naval Ravikant' },
	{ q: 'Riqueza é habilidade multiplicada.', a: 'Naval Ravikant' },
	{ q: 'Desejo é contrato com a infelicidade.', a: 'Naval Ravikant' },
	{ q: 'Simplicidade escala.', a: 'Naval Ravikant' },
	{ q: 'O jogo longo vence o impulso curto.', a: 'Naval Ravikant' }
];
