-- ============================================================
-- Pag's Up — ordem de lançamento dos pagamentos
--
-- O painel do financeiro (/pagamentos/<token>) passa a listar os pagamentos na
-- ordem em que foram lançados, em vez de agrupados por categoria: o financeiro
-- acompanha a lista de cima para baixo, e o que entrou por último fica no fim.
--
-- created_at não basta para isso. "Finalizar" o cronograma lança vários
-- pagamentos num insert só, e todos saem com o MESMO created_at (em 29/09/2026,
-- dez pagamentos às 18:48:10.343). Daí a coluna própria: uma sequência, que o
-- banco numera na ordem das linhas do insert.
--
-- As linhas que já existiam são numeradas por created_at e, dentro do mesmo
-- lançamento, pela posição física (ctid), que é a ordem em que entraram.
--
-- Idempotente (a numeração inicial só roda quando a coluna nasce).
--   PGPASSWORD='***' node scripts/run_migration.mjs supabase/migrations/0070_pagsup_ordem_de_lancamento.sql
-- ============================================================

do $$
begin
	if not exists (
		select 1 from information_schema.columns
		where table_schema = 'public' and table_name = 'pagsup_pagamentos' and column_name = 'ordem'
	) then
		alter table public.pagsup_pagamentos
			add column ordem bigint generated by default as identity;

		update public.pagsup_pagamentos p
			set ordem = n.rn
			from (
				select id, row_number() over (order by created_at, ctid) as rn
				from public.pagsup_pagamentos
			) n
			where n.id = p.id;

		perform setval(
			pg_get_serial_sequence('public.pagsup_pagamentos', 'ordem'),
			coalesce((select max(ordem) from public.pagsup_pagamentos), 0) + 1,
			false
		);
	end if;
end $$;

comment on column public.pagsup_pagamentos.ordem is
	'Sequência de lançamento. Pagamentos lançados juntos ficam na ordem das linhas do insert.';

create index if not exists idx_pagsup_pagamentos_ordem
	on public.pagsup_pagamentos (cliente_id, ordem);

-- O painel público passa a seguir a ordem de lançamento (era por categoria).
create or replace function public.pagsup_publico(p_token uuid, p_mes text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
	v_cliente public.pagsup_clientes%rowtype;
	v_meses text[];
	v_mes text;
begin
	if p_token is null then
		return null;
	end if;

	select * into v_cliente from public.pagsup_clientes where token_publico = p_token;
	if not found then
		return null;
	end if;

	select coalesce(array_agg(m order by m desc), '{}')
		into v_meses
		from (
			select distinct to_char(data_pagamento, 'YYYY-MM') as m
			from public.pagsup_pagamentos
			where cliente_id = v_cliente.id
		) s;

	v_mes := case when p_mes = any (v_meses) then p_mes else v_meses[1] end;

	return jsonb_build_object(
		'cliente', v_cliente.nome,
		'meses', to_jsonb(v_meses),
		'mes', v_mes,
		'pagamentos', coalesce((
			select jsonb_agg(
				jsonb_build_object(
					'id', p.id,
					'prestador', p.prestador_nome,
					'servico', p.servico,
					'regiao', p.regiao,
					'lj', p.lj,
					'data', p.data_pagamento,
					'valor', p.valor,
					'doc_tipo', p.doc_tipo,
					'doc_arquivo', p.doc_arquivo,
					'doc_apagado_em', p.doc_apagado_em
				)
				order by p.ordem
			)
			from public.pagsup_pagamentos p
			where p.cliente_id = v_cliente.id
				and to_char(p.data_pagamento, 'YYYY-MM') = v_mes
		), '[]'::jsonb)
	);
end;
$$;

revoke all on function public.pagsup_publico(uuid, text) from public;
grant execute on function public.pagsup_publico(uuid, text) to anon, authenticated;

notify pgrst, 'reload schema';
