-- ============================================================
-- DMetric — "Última hora" e "Últimas 24 horas"
--
-- Os contadores (dmetric_diario) são por DIA: não respondem "quantos na última
-- hora". Daí uma lista curta de acessos, um por linha, que guarda só as últimas
-- 48 horas (a faxina sai junto com a dos vistos, dentro da coleta). É dela que
-- os filtros de hora e de 24 horas leem — com visitante distinto de verdade,
-- já que a lista é pequena. Os períodos de dias continuam nos contadores.
--
-- Sem IP e sem nada que identifique a pessoa: o visitante é o mesmo hash
-- diário dos contadores (0072). Uma pessoa que atravessa a meia-noite dentro
-- das 24 horas conta duas vezes — o hash troca no dia novo.
--
-- Idempotente.
--   PGPASSWORD='***' node scripts/run_migration.mjs supabase/migrations/0077_dmetric_recentes.sql
-- ============================================================

create table if not exists public.dmetric_recentes (
	id bigint generated by default as identity primary key,
	site_id uuid not null references public.dmetric_sites (id) on delete cascade,
	em timestamptz not null default now(),
	-- 'v' = página vista; 'tempo' = segundos de tela; 'clique'
	tipo text not null,
	visitante text,
	caminho text,
	origem text,
	campanha text,
	pais text,
	cidade text,
	dispositivo text,
	navegador text,
	sistema text,
	valor text,
	segundos integer not null default 0
);
create index if not exists idx_dmetric_recentes_em on public.dmetric_recentes (em);
create index if not exists idx_dmetric_recentes_site_em on public.dmetric_recentes (site_id, em);

alter table public.dmetric_recentes enable row level security;
drop policy if exists dmetric_recentes_ver on public.dmetric_recentes;
create policy dmetric_recentes_ver on public.dmetric_recentes
	for select to authenticated using (public.tem_permissao('dmetric', 'ver'));

-- ---------- Coleta: além dos contadores, a linha recente ----------
create or replace function public.dmetric_coletar(
	p_segredo text,
	p_chave text,
	p_host text,
	p_caminho text,
	p_origem text,
	p_campanha text,
	p_pais text,
	p_cidade text,
	p_dispositivo text,
	p_navegador text,
	p_sistema text,
	p_visitante text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
	v_site uuid;
	v_dia date := (now() at time zone 'America/Sao_Paulo')::date;
	v_nova boolean;
	v_n integer;
	v_pais text := upper(left(coalesce(p_pais, ''), 2));
	v_cidade text := left(coalesce(p_cidade, ''), 80);
	v_caminho text := left(coalesce(nullif(p_caminho, ''), '/'), 200);
	v_origem text := left(coalesce(nullif(p_origem, ''), 'Direto'), 120);
begin
	if not public.dmetric_segredo_ok(p_segredo) then
		return false;
	end if;
	v_site := public.dmetric_site(p_chave, p_host);
	if v_site is null then
		return false;
	end if;

	insert into public.dmetric_vistos (site_id, dia, visitante)
		values (v_site, v_dia, left(p_visitante, 64))
		on conflict do nothing;
	get diagnostics v_n = row_count;
	v_nova := v_n > 0;

	insert into public.dmetric_diario as d (site_id, dia, dimensao, valor, visitas, visualizacoes)
	select v_site, v_dia, x.dimensao, x.valor, case when v_nova then 1 else 0 end, 1
	from (values
		('total', ''),
		('pais', v_pais),
		('cidade', v_cidade),
		('pagina', v_caminho),
		('dispositivo', left(coalesce(p_dispositivo, ''), 30)),
		('navegador', left(coalesce(p_navegador, ''), 30)),
		('sistema', left(coalesce(p_sistema, ''), 30))
	) as x(dimensao, valor)
	-- Origem e campanha só contam na chegada (ver 0072).
	union all
	select v_site, v_dia, 'origem', v_origem, 1, 1
	where v_nova
	union all
	select v_site, v_dia, 'campanha', left(p_campanha, 120), 1, 1
	where v_nova and coalesce(p_campanha, '') <> ''
	on conflict (site_id, dia, dimensao, valor) do update
		set visitas = d.visitas + excluded.visitas,
			visualizacoes = d.visualizacoes + excluded.visualizacoes;

	insert into public.dmetric_recentes
		(site_id, tipo, visitante, caminho, origem, campanha, pais, cidade, dispositivo, navegador, sistema)
	values
		(v_site, 'v', left(p_visitante, 64), v_caminho, v_origem, nullif(left(coalesce(p_campanha, ''), 120), ''),
		 v_pais, v_cidade, left(coalesce(p_dispositivo, ''), 30), left(coalesce(p_navegador, ''), 30),
		 left(coalesce(p_sistema, ''), 30));

	update public.dmetric_sites set ultima_visita = now()
		where id = v_site and (ultima_visita is null or ultima_visita < now() - interval '1 minute');

	-- Faxina de vez em quando: vistos de anteontem para trás e recentes de mais de 48 h.
	if random() < 0.02 then
		delete from public.dmetric_vistos where dia < v_dia - 1;
		delete from public.dmetric_recentes where em < now() - interval '48 hours';
	end if;

	return true;
end;
$$;

-- ---------- Tempo e cliques: também na lista recente ----------
create or replace function public.dmetric_evento(
	p_segredo text,
	p_chave text,
	p_host text,
	p_caminho text,
	p_tipo text,
	p_valor text,
	p_segundos integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
	v_site uuid;
	v_dia date := (now() at time zone 'America/Sao_Paulo')::date;
	v_seg integer := least(greatest(coalesce(p_segundos, 0), 0), 1800);
	v_caminho text := left(coalesce(nullif(p_caminho, ''), '/'), 200);
begin
	if not public.dmetric_segredo_ok(p_segredo) then
		return false;
	end if;
	v_site := public.dmetric_site(p_chave, p_host);
	if v_site is null then
		return false;
	end if;

	if p_tipo = 'tempo' and v_seg > 0 then
		insert into public.dmetric_diario as d (site_id, dia, dimensao, valor, segundos)
		values
			(v_site, v_dia, 'total', '', v_seg),
			(v_site, v_dia, 'pagina', v_caminho, v_seg)
		on conflict (site_id, dia, dimensao, valor) do update
			set segundos = d.segundos + excluded.segundos;
		insert into public.dmetric_recentes (site_id, tipo, caminho, segundos)
			values (v_site, 'tempo', v_caminho, v_seg);
		return true;
	end if;

	if p_tipo = 'clique' and coalesce(p_valor, '') <> '' then
		insert into public.dmetric_diario as d (site_id, dia, dimensao, valor, visualizacoes)
		values (v_site, v_dia, 'clique', left(p_valor, 80), 1)
		on conflict (site_id, dia, dimensao, valor) do update
			set visualizacoes = d.visualizacoes + 1;
		insert into public.dmetric_recentes (site_id, tipo, caminho, valor)
			values (v_site, 'clique', v_caminho, left(p_valor, 80));
		return true;
	end if;

	return false;
end;
$$;

-- ---------- Painel das últimas horas ----------
-- O mesmo formato de dmetric_painel (0074), lido da lista recente, mais a
-- `serie`: a linha do tempo em degraus de p_passo (5 min na última hora, 1 h
-- nas 24 horas), já com os degraus vazios.
create or replace function public.dmetric_painel_recente(p_site uuid, p_desde timestamptz, p_passo interval)
returns jsonb
language sql
stable
set search_path = public
as $$
	with r as (
		select * from public.dmetric_recentes
		where em >= p_desde and (p_site is null or site_id = p_site)
	),
	v as (select * from r where tipo = 'v'),
	-- A primeira página de cada visitante na janela: é dela a origem e a campanha.
	chegada as (
		select distinct on (site_id, visitante) * from v order by site_id, visitante, em
	),
	dims as (
		select 'pais' as dimensao, pais as valor, count(distinct (site_id, visitante))::int as visitas, count(*)::int as visualizacoes from v group by pais
		union all select 'cidade', cidade, count(distinct (site_id, visitante))::int, count(*)::int from v group by cidade
		union all select 'pagina', caminho, count(distinct (site_id, visitante))::int, count(*)::int from v group by caminho
		union all select 'dispositivo', dispositivo, count(distinct (site_id, visitante))::int, count(*)::int from v group by dispositivo
		union all select 'navegador', navegador, count(distinct (site_id, visitante))::int, count(*)::int from v group by navegador
		union all select 'sistema', sistema, count(distinct (site_id, visitante))::int, count(*)::int from v group by sistema
		union all select 'origem', origem, count(*)::int, count(*)::int from chegada group by origem
		union all select 'campanha', campanha, count(*)::int, count(*)::int from chegada where campanha is not null group by campanha
		union all select 'clique', valor, 0, count(*)::int from r where tipo = 'clique' group by valor
	),
	degraus as (
		select g as momento
		from generate_series(
			date_bin(p_passo, p_desde, timestamptz '2000-01-01'),
			date_bin(p_passo, now(), timestamptz '2000-01-01'),
			p_passo
		) g
	),
	por_degrau as (
		select date_bin(p_passo, em, timestamptz '2000-01-01') as momento,
			count(distinct (site_id, visitante))::int as visitas, count(*)::int as visualizacoes
		from v group by 1
	)
	select jsonb_build_object(
		'visitas', (select count(distinct (site_id, visitante)) from v),
		'visualizacoes', (select count(*) from v),
		'segundos', coalesce((select sum(segundos) from r where tipo = 'tempo'), 0),
		'por_dia', '[]'::jsonb,
		'serie', coalesce((
			select jsonb_agg(jsonb_build_object('momento', d.momento, 'visitas', coalesce(p.visitas, 0), 'visualizacoes', coalesce(p.visualizacoes, 0)) order by d.momento)
			from degraus d left join por_degrau p using (momento)
		), '[]'::jsonb),
		'dimensoes', coalesce((
			select jsonb_object_agg(dimensao, itens) from (
				select dimensao, jsonb_agg(jsonb_build_object('valor', coalesce(valor, ''), 'visitas', visitas, 'visualizacoes', visualizacoes)
					order by visitas desc, visualizacoes desc) as itens
				from dims group by dimensao
			) x
		), '{}'::jsonb)
	);
$$;
grant execute on function public.dmetric_painel_recente(uuid, timestamptz, interval) to authenticated;

-- A lista de sites para as últimas horas (o par de dmetric_por_site, 0076).
create or replace function public.dmetric_por_site_recente(p_desde timestamptz)
returns table (site_id uuid, visitas integer, visualizacoes integer, segundos bigint, cliques integer)
language sql
stable
set search_path = public
as $$
	select
		site_id,
		count(distinct visitante) filter (where tipo = 'v')::int,
		count(*) filter (where tipo = 'v')::int,
		coalesce(sum(segundos) filter (where tipo = 'tempo'), 0)::bigint,
		count(*) filter (where tipo = 'clique')::int
	from public.dmetric_recentes
	where em >= p_desde
	group by site_id;
$$;
grant execute on function public.dmetric_por_site_recente(timestamptz) to authenticated;

notify pgrst, 'reload schema';
